'use strict';

const { Queue } = require('bullmq');
const redisClient = require('../config/redis');
const logger = require('../utils/logger');

/**
 * Email Queue (BullMQ)
 * --------------------
 * Job payload shape:
 * {
 *   email      : String  — recipient address (from the Lead collection)
 *   subject    : String  — generated by templateEngine
 *   html       : String  — generated by templateEngine
 *   text       : String  — plain-text fallback
 * }
 */
const emailQueue = new Queue(process.env.QUEUE_NAME || 'email-queue', {
  connection: redisClient,
  defaultJobOptions: {
    attempts: parseInt(process.env.SMTP_MAX_RETRIES, 10) || 3,
    backoff: {
      type: 'exponential',
      delay: 5000, // 5 s → 10 s → 20 s
    },
    removeOnComplete: { age: 3600,  count: 5000 },
    removeOnFail:     { age: 86400 },
  },
});

emailQueue.on('error', (err) =>
  logger.error(`[emailQueue] error: ${err.message}`)
);

logger.info(`[emailQueue] "${emailQueue.name}" ready`);
module.exports = emailQueue;
